name: Check for formatting issues

on:
  pull_request:
    branches:
      - development

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Format
        run: bun format

      - name: Check for formatting issues
        run: bun lint

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global pull.rebase false
          git add -A
          git pull --rebase origin HEAD:${{ github.head_ref }}
          git push origin HEAD:${{ github.head_ref }}
