name: Build TypeScript

on:
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Corepack Enable
      run: corepack enable
      
    - name: Yarn Stable
      run: yarn set version stable
      
    - name: Install TypeScript
      run: npm i -g typescript
        
    - name: Install dependencies
      run: yarn install
    
    - name: Pull Submodules
      run: git submodule update --init --recursive
    
    - name: Copy Configs
      run: cp src/Constants.example.ts src/Constants.ts && cp src/Config.example.ts src/Config.ts
      
    - name: Version Outputs
      run: "echo \"TypeScript Version: $(tsc -v) | Yarn Version: $(yarn -v) | Node Version: $(node -v)\""
      
    - name: Build TypeScript
      run: tsc -p . --noEmit
